version: '3'
services:
  app:
    image: node:12.18.0-slim
    working_dir: "/app"
    command: sh -c "cd react-sample && yarn && yarn start"
    ports:
      - "3000:3000"
    volumes:
     - ./app:/app/
    tty: true
